version: 2.1

jobs:
  update-text-file:
    docker:
      - image: cimg/go:1.18.4
    steps:
      - checkout
      - run:
          name: "create title.txt"
          command: |
            cd batch
            go run main.go
      - run:
          name: "commit title.txt to target repository"
          command: |
            cd batch
            git clone https://${GITHUB_PERSONAL_ACCESS_TOKEN}@github.com/tokizuoh/${TEXT_FILE_REPOSITORY}
            mv title.txt ${TEXT_FILE_REPOSITORY}/title.txt
            cd ${TEXT_FILE_REPOSITORY}
            git config user.email ${GITHUB_EMAIL}
            git config user.name "tokizuoh+circleci"
          
            git checkout -b circleci-update-title-txt
            git add title.txt
            git commit -m '[CircleCI] update title.txt' || true
            git push origin HEAD:develop

workflows:
  update-text-file:
    triggers:
      - schedule:
        # Every day, At 00:00
        cron: "0 0 * * *"
        filters:
          branches:
            only:
              - develop
    jobs:
      - update-text-file
